Update association_proxy.rb
The metaclass defined here is causing the problem when I try to store her::Model object in Rails.cache with file_store. See the example below. Because if this I am not able to use latest her version in my project. Rails cache works fine with her version 0.6.8 after that it gives following error. 

```
[2] first »  metaclass = (class << self; self; end) 
=> #<Class:#<Object:0x000000017ce3f8>> < Object
[3] first »  Marshal.dump(metaclass)
TypeError: singleton class can't be dumped
from (pry):3:in `dump'
```